config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://backend.local/guestbook"
image:
  repository: phico/frontend
  tag: "2.0"
replicaCount: 1
service:
  type: ClusterIP
  port: 80
ingress:
  host: frontend.local